import copy


def mask_values(data: dict, masks: list[(str, str)]) -> dict:
    """
    Mask fields in the response data which are unpredictable and not important. Primarily used
    to mask unique ids generated by the database with a predictable (and test assertable) value.
    """
    masked_data = copy.deepcopy(data)
    for key, replacement_value in masks:
        masked_data[key] = replacement_value
    return masked_data
